name: Example Workflow

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  my_custom_action_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Custom Action
        uses: ./ItBeginsWCC/GitHubActionsWorkflows@v0.0.8
        with:
          app_name: ${{ github.event.repository.name }}
          language: 'go'