# on: [pushV]
on:
  workflow_dispatch:
  # pull_request:
name: Analysis Shifleft
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test Analysis Action
        uses: ItBeginsWCC/shiftleft-docker-analysis@v11.0.3
        with:
          shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          language: 'go'
          go-version: '1.17'
          app-name: 'shiftleft-go-demo'
          app-path: './...'

  Build-Rules:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: test-action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Checkout Test Repository
        uses: actions/checkout@v2
        with:
          repository: ItBeginsWCC/Break-The-Build

      - name: Show yml file
        run: |
          find -name shiftleft.yml
          cat ./.btb/shiftleft.yml
      # - name: Copy ShiftLeft Config
      #   run: |
      #     # Copy the shiftleft.yml file to the root directory
      #     cp shiftleft.yml $GITHUB_WORKSPACE/
      # - name: Download ShiftLeft Config
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: shiftleft-config
      #     path: $GITHUB_WORKSPACE/
      # - name: Upload Artifactory
      #   uses: ItBeginsWCC/break-the-build-docs@v2.5
      #   with:
      #     repo-name: ItBeginsWCC/shiftleft-go-demo
      # - name: Download Artifact
      #   run: wget https://github.com/yourusername/your-repo/raw/master/your-artifact.zip
      # - name: Unzip Artifact 
      #   run: unzip your-artifact.zip
      # - name: Download ShiftLeft Config
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: shiftleft-config
      #     path: $GITHUB_WORKSPACE/
      - name: Break The Build Analysis Action
        uses: ItBeginsWCC/Break-The-Build@v5.5
        with:
          shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          app-name: 'shiftleft-go-demo'
          break-the-build: 'Y'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repo-name: ${{ github.workspace }}
