on: [push]
name: Analysis Shifleft
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test Analysis Action
        uses: ItBeginsWCC/shiftleft-docker-analysis@v11.0.1
        with:
          shiftleft-access-token: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
          language: 'go'
          go-version: '1.17'
          app-name: 'shiftleft-go-demo'
          app-path: './...'
          break-the-build: 'Y'